### ISSUE TITLE
`compare_config()` returns non-printable characters

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#10]
After I load a replace candidate the `compare_config()` returns for me non-printable characters (probably result of 'dots loading animation' in CLI)
```
>>> device.compare_config()
'...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08'
```
(note: the loaded candidate config should change no config in running config)

**Comment by jgcumming** [comment]
Please clarify this element of the issue: (note: the loaded candidate config should change no config in running config)

Please raise a separate issue if this is happening

**Comment by omron93** [comment]
>(note: the loaded candidate config should change no config in running config)

I meant that I've opened the device -> retrieved the running config -> removed MOTD (#7) and persistent-indices (#9) -> loaded the updated running config as a replace candidate -> did compare_config()

So just wanted to highlight that there should be no diff and compare_config() somehow looks correct. The only issue is that after the above operations the compare_config() started to return the non-printable character as in the issue description.

**Comment by JonLundstrom** [comment]
omron93, we have not been able to reproduce this. As part of our investigation, we have the following disabled in SROS, which may avoid your issue. Can you please retest with "environment progress-indicator admin-state disable"?

**Comment by omron93** [comment]
I can no longer reproduce it using XML configurations.
