### ISSUE TITLE
Documentation: get_config() using SSH

### ISSUE THREAD

**Issue by abudilov** [napalm-automation-community/napalm-sros#12]
### Description:
The documentation should specify that the current driver code is using SSH for the get_config() method and **not** NETCONF. 

[Install.md](https://github.com/napalm-automation-community/napalm-sros/blob/master/Install.md) should include "console true" in order to make it work:

```
user "netconf" {
        password "<hash>"
        access {
            console true
            netconf true
        }
        console {
            member ["administrative"]
        }
    }
```

**Comment by JonLundstrom** [comment]
Completed pull request. #15 Let us know if any other issues are found.
