### ISSUE TITLE
integration into bigger napalm project?

### ISSUE THREAD

**Issue by shorton3** [napalm-automation-community/napalm-sros#13]
Any guidance on how to integrate this into the bigger Napalm project?  What to put in _SUPPORTED_DRIVERS.py?  How to call it using the napalm command line utility?  I tried, but seems like there is some inconsistency in the package naming: napalm_sros, napalm-sros, sros? Thanks

**Comment by prezes71** [comment]
Enter git repository on your local PC, install requirements: **_pip install -r requirements.txt_**, then _**python setup.py install**_. After that it should be accessible in Network_Driver definitions.
