### ISSUE TITLE
Command get_mac_address_table return error with incorrect path to text parser.

### ISSUE THREAD

**Issue by prezes71** [napalm-automation-community/napalm-sros#14]
Command get_mac_address_table return error with incorrect path text parser (Centos 8, python 3.9.1)

Traceback (most recent call last):
  File "/opt/venv/scripts/napalm_test.py", line 23, in <module>
    sros_out3=device.get_mac_address_table()
  File "/opt/venv/lib/python3.9/site-packages/napalm_sros-0.1.0-py3.9.egg/napalm_sros/sros.py", line 2165, in get_mac_address_table
    output_list = parse_with_textfsm(template, buff)
  File "/opt/venv/lib/python3.9/site-packages/napalm_sros-0.1.0-py3.9.egg/napalm_sros/utils/parse_output_to_dict.py", line 11, in parse_with_textfsm
    with open(os.path.join(os.path.dirname(os.path.realpath(__file__)), template), "r") as template_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venv/lib/python3.9/site-packages/napalm_sros-0.1.0-py3.9.egg/napalm_sros/utils/**textfsm_templates\\nokia_sros_show_service_fdb_mac.tpl**'

Line 2162 - 2165
>         cmd = "show service fdb-mac"
>         buff = self._perform_cli_commands(["environment more false", cmd])
>         template = "textfsm_templates\\nokia_sros_show_service_fdb_mac.tpl"
>         output_list = parse_with_textfsm(template, buff)

Replacing '//' with '\' resolves the issue, however it should be adapted automatically.

**Comment by ashah26** [comment]
Hey,

Actually for me it works both ways with a "//" and "\\" 
Can you tell me some more specifics so I can try to reproduce the same ?

**Comment by JonLundstrom** [comment]
No further comments/ concerns from prezes71, so at this point, we'll close this issue.
