### ISSUE TITLE
Not following napalm interface

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#18]
Hi,
please follow napalm "interface" so this driver for SROS is interchangeable with other vendors and compatible with wrappers like [napalm-ansible](https://github.com/napalm-automation/napalm-ansible).

It's great that now it's possible to do more performant diffs with xml format, but first issue I've seen is that the `compare_config()` signature is different and doing the compare with config in function arguments is not compatible with napalm and other tools.

This repo seems to have unit tests for comparing signature of the driver with upstream base driver. But this probably wasn't run
> E       AssertionError: Some methods vary. 
E       dict_keys(['compare_config', 'get_config', 'ping', 'traceroute'])

Also `xmltodict` and `dictdiffer` dependencies are missing in the requirements files.

**Comment by omron93** [comment]
For `format="xml"` argument in `get_config`, I guess the way how to not break the napalm compatibility is to set sensible default and probably to allow changing that in per-driver-object setting in the constructor - see `optional_args` in https://napalm.readthedocs.io/en/latest/base.html?highlight=compare_config#napalm.base.base.NetworkDriver

**Comment by JonLundstrom** [comment]
> Hi,
> please follow napalm "interface" so this driver for SROS is interchangeable with other vendors and compatible with wrappers like [napalm-ansible](https://github.com/napalm-automation/napalm-ansible).
> 
> It's great that now it's possible to do more performant diffs with xml format, but first issue I've seen is that the `compare_config()` signature is different and doing the compare with config in function arguments is not compatible with napalm and other tools.
> 
> This repo seems to have unit tests for comparing signature of the driver with upstream base driver. But this probably wasn't run
> 
> > E       AssertionError: Some methods vary.
> > E       dict_keys(['compare_config', 'get_config', 'ping', 'traceroute'])
> 
> Also `xmltodict` and `dictdiffer` dependencies are missing in the requirements files.

Thanks for the feedback. We'll take a look a today and see what the issue is.
