### ISSUE TITLE
compare_config doesn't return human readable string

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#20]
When doing compare_config() with configs in XML format, the compare_config doesn't return human readable string.

From napalm docs:
>A string showing the difference between the running configuration and the candidate configuration.
https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.compare_config

Currently the compare_config() returns dictionary and the output contains the xml namespaces, which isn't very human friendly and readable.

**Comment by JonLundstrom** [comment]
@omron93 An optional argument has been added to support a new compare results format. We believe it should eliminate your concerns about readability. Comments welcome.
