### ISSUE TITLE
GET_NETWORK_INSTANCES tries to do an unsupported operation

### ISSUE THREAD

**Issue by Anchovy76** [napalm-automation-community/napalm-sros#23]
In nc_filters.py a list of VPLS interfaces is queried. However there is no such element possible under a VPLS service, only SAP or EVPN attachments can be done. This results in:

>>> print(device.get_network_instances(name=""))
ncclient.operations.rpc.RPCError: 
            MINOR: MGMT_CORE #2201: Unknown element

When you remove the VPLS service from filters below and only query base router and VPRN hierarchy this works fine.

Related code block listed below.

**Comment by Anchovy76** [comment]
`GET_NETWORK_INSTANCES = {
    "_": """
    <filter>
        <state xmlns="urn:nokia.com:sros:ns:yang:sr:state">
            <router>
                <router-name>{instance_name}</router-name>
                <interface>
                    <interface-name/>
                </interface>
            </router>
            <service>
                <vprn>
                    <service-name>{instance_name}</service-name>
                    <oper-route-distinguisher/>
                    <interface>
                        <interface-name/>
                    </interface>
                </vprn>
                <vpls>
                    <service-name>{instance_name}</service-name>
                    <interface>
                        <interface-name/>
                    </interface>
                </vpls>
            </service>
        </state>
    </filter>
    """
}`

**Comment by ashah26** [comment]
VPLS services with the Get_network_instances method. i.e, an interface can be returned if the VPLS has a routed-vpls interface created, but if one is not present, just the VPLS name and state will be returned. 
Updated the code in #25 PR.

**Comment by JonLundstrom** [comment]
@Anchovy76 Let us know when you get a chance to eval the change we made. Thanks for the interest in advance.

**Comment by Anchovy76** [comment]
Sorry for the late reply, but yes, this seems to work now. Thanks for fixing it.
