### ISSUE TITLE
Getting running config and then loading it back fails

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#3]
I've configured Nokia 7750 SR-2s device following the installation guide from this repo.

I can connect to the device and I can get the running config, but it fails when I try to load the obtained config back.

```python
>>> device.open()
>>> config = device.get_config()['running']
>>> device.load_replace_candidate(config=config)
Traceback (most recent call last):
  File "/srv/conda/envs/python3.6/lib/python3.6/site-packages/napalm_sros/sros.py", line 376, in load_replace_candidate
    raise ReplaceConfigException()
napalm.base.exceptions.ReplaceConfigException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/conda/envs/python3.6/lib/python3.6/site-packages/napalm_sros/sros.py", line 378, in load_replace_candidate
    raise ReplaceConfigException(rex)
napalm.base.exceptions.ReplaceConfigException
```

Note: the obtained running config is a string with no new lines.

Can this failure be related to any device config setting? Or how to fix this?

**Comment by ashah26** [comment]
Thanks for pointing that out, our code currently supports configs pushed with "\n" after each line. That said, we will evaluate updating the driver to support configs without "\n" being pushed. Timing of those adds is unknown at this time.
