### ISSUE TITLE
napalm-sros is incompatible with napalm 4.0.0

### ISSUE THREAD

**Issue by rasanentimo** [napalm-automation-community/napalm-sros#62]
### Steps to reproduce

While napalm-sros 1.0.1 works with napalm 3.4.1/netmiko 3.4.0/textfsm 1.1.3, it doesn't work with Napalm 4.0.0

Install napalm-sros with pip with napalm 4.0.0

pip install git+https://github.com/napalm-automation-community/napalm-sros.git

### Current behaviour

Napalm 4.0.0 has pinned netmiko version 

netmiko>=4.1.0

https://github.com/napalm-automation/napalm/blob/develop/requirements.txt#L11

and Netmiko 4.1.2 has pinned textfsm version 

textfsm==1.1.2

https://github.com/ktbyers/netmiko/blob/develop/setup.py#L55

### Expected behaviour

Napalm-sros would be installed

**Comment by jbemmel** [comment]
Same issue has recently been fixed in napalm-automation, see https://github.com/napalm-automation/napalm/pull/1783

Should be resolved once pinning is reverted in Netmiko too

**Comment by jbemmel** [comment]
Netmiko was fixed: https://github.com/ktbyers/netmiko/pull/3003/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
