### ISSUE TITLE
No way to disable logging to ./logs-... file

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-sros#70]
The [init_logging()](https://github.com/napalm-automation-community/napalm-sros/blob/master/napalm_sros/utils/utils.py#L7-L12) adds logging to a file in current working directory.

But because the sros napalm driver is loaded "dynamically" from napalm library (`get_network_driver()` function), it's very hard to disable this logging to file and use different logging setup (e.g. to syslog, or even no logging).

Please add possibility to disable this logging file handler and not changing logging module setting.

**Comment by jbemmel** [comment]
See https://github.com/napalm-automation-community/napalm-sros/pull/71

There was no need to do custom log configuration, let's remove it
